### ISSUE TITLE
Can I disable caps + ctrl switching?

### ISSUE THREAD

**Issue by hwooo** [AdamJel/win-capslock-usefull#1]
Currently `caps lock + t` and `caps lock + ctrl` both are same shortcuts for switching cases.

Is it possible to disable `caps lock + ctrl`? I can't find where do I have to modify in the script code.

**Comment by AdamJel** [comment]
Hi, do you have the current code? The CapsLock + Ctrl should have been turned off by [this commit](https://github.com/AdamJel/win-capslock-usefull/commit/061a350a86a0cd003be025921dcd8c7d1c152449). Only CapsLock + t should work now. Also, you need to manually terminate all other autohotkey scripts, or otherwise they run in parallel and may interfere with each other (autohotkey does union of sets if possible).

**Comment by hwooo** [comment]
Thanks for reply. If holding down Caps Lock or Ctrl for some time and then press Ctrl/Caps, it causes case switching with a very high probability. At this time, each time I press Caps Lock, 'Caps Lock' LED indicator on the keyboard blinks. (it doesn't blink when there is no case switching issue) I think this is not an intended behavior, and I'm wondering is this a problem of the code, or Autohotkey itself.

**Comment by AdamJel** [comment]
Unfortunately I am unable to replicate that behaviour. No interaction of Caps Lock and Ctrl causes case switching nor blinking for me. Tested on 2 machines. I must repeat the advice to check, if something else is not interfering with autohotkey, perhaps custom key bindings of IDE or proprietary keyboard software, etc.

**Comment by AdamJel** [comment]
Hi @hwooo, have you been able to resolve the issue, or does the problem persist? If it persists, can you give me more details on the observed behaviour?

**Comment by hwooo** [comment]
@AdamJel Hi. Currently, the problem doesn't occur anymore. I think I can close this issue. Thanks!
